# Entidade/Tabela que armazena os dados dos usuários do sistema.

[[fields]]
field = "id"
sqlite.type = "TEXT"
description = "O identificador único da unidade do usuário (UUID)."
example = "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"

[[fields]]
field = "nome"
sqlite.type = "TEXT"
description = "Nome do usuário"
example = "João da Silva"

[[fields]]
field = "login"
sqlite.type = "TEXT"
description = "Login do usuário (pode ser CPF, e-mail, etc.)"
example = "123.456.789-10"

# @Deprecated: Informações podem ser inseridas no campo 'descrição' e não possuem utilidade
[[fields]]
field = "email"
sqlite.type = "TEXT"
description = "e-mail do usuário"
example = "mail@example.com"

[[fields]]
field = "hashed_password"
sqlite.type = "TEXT"
description = "Hash da senha do usuário com salt"
example = "mv853wa9n5auohfd083hhp45"

# @Deprecated: Informações podem ser inseridas no campo 'descrição' e não possuem utilidade
[[fields]]
field = "identificacao"
sqlite.type = "TEXT"
description = "Documento de identificação do usuário (CPF e/ou RG)"
example = "123.456.789-10"

# @Deprecated: Informações podem ser inseridas no campo 'descrição' e não possuem utilidade
[[fields]]
field = "cargo"
sqlite.type = "TEXT"
description = "Cargo do funcionário"
example = "Gerente de Estoque"

[[fields]]
field = "descricao"
sqlite.type = "TEXT"
description = "Descrição ou observações sobre o funcionário"
example = "N/A"

[[fields]]
field = "habilitado"
description = "Habilita/Desabilita login do usuário (1 para true, 0 para false)"
sqlite.type = "INTEGER"
example = "1"

[[fields]]
field = "modo_escuro"
sqlite.type = "INTEGER"
description = "Preferência do usuário para o modo escuro (1 para true, 0 para false)"
example = "1"

[[fields]]
field = "nivel_permissoes"
sqlite.type = "INTEGER"
description = """
Define o nível de acesso do usuário.
# 0: administrador (Consegue alterar configurações e adicionar novos usuários)
# 1: cadastro (Consegue realizar o cadastro de produtos)
# 2: controle (Consegue realizar o controle de quantidades de estoque)
# 3: leitura (Consegue apenas visualizar informações)
"""
example = "1"

# campo pode ser blob (base64) ou text
[[fields]]
field = "foto"
sqlite.type = "TEXT"
description = "URL da foto de perfil do usuário"
example = "https://example.com/foto.jpg"

[[fields]]
field = "criado_em"
sqlite.type = "DATETIME"
description = "Data/Hora que o usuário foi criado."
example = "https://example.com/foto.jpg"

# @Deprecated: A aplicação irá manter logs separados desse tipo de informação
[[fields]]
field = "criado_por"
sqlite.type = "DATETIME"
description = "Usuário que criou o usuário."
example = "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"

[[fields]]
field = "created_at"
sqlite.type = "DATE"
description = "Data/Hora que o usuário foi criado."
example = "2018-09-15"

[[fields]]
field = "updated_at"
sqlite.type = "integer"
description = "Data da última atualização do registro"
example = "2018-09-15"

# TODO: talvez: ultimo_login ou criar uma tabela de historico de login?
# habilitado: Verificar oturas opções
