"$schema" = "https://json.schemastore.org/prettierrc"

bracketSameLine = true
trailingComma = "all"
endOfLine = "crlf"
bracketSpacing = true
printWidth = 80

plugins = ["@trivago/prettier-plugin-sort-imports"]
importOrderSortSpecifiers = true
