"$schema" = "https://json.schemastore.org/prettierrc"

bracketSameLine = true
trailingComma = "all"
endOfLine = "crlf"
bracketSpacing = true
printWidth = 80

plugins = ["prettier-plugin-organize-imports"]
