"$schema" = "https://www.schemastore.org/prettierrc.json"

semi = false
singleQuote = true
printWidth = 100
endOfLine = "crlf"
bracketSpacing = true
trailingComma = "all"
bracketSameLine = false

plugins = ["prettier-plugin-organize-imports"]
